### ISSUE TITLE
Secrets

### ISSUE THREAD

**Issue by didierverna** [european-lisp-symposium/els-web#10]
We need to improve the handling of secrets. Currently, the secrets file also contains things that are not secret. When multiple people edit the site, this makes it difficult to let everyone generate the pages: this means sharing only part of the secrets file, and since it cannot be included in the repo, even the public data cannot be updated properly.

Currently, I think the Google API key is not really a secret. Maybe it could be defined somewhere else globally (or per-page)? Sme for the Stripe public key (either store it globally or make it part of DEFINE-REGISTRATION)? What else?

**Comment by Shinmera** [comment]
The reason they're secrets is because they're supposed to be details of the one hosting the website, rather than part of actual edition data.

I'm not sure it's a good idea anymore to include the generated data in this repository at all. I initially did it as a trick to make hosting on github faster. However, now that collaboration is in place this makes things messy.

What ideally should be happening is that only the webmaster with the proper secrets file generates the data that is actually shown live. This can be done as a cronjob or something that regularly pulls and regenerates, and should not be done by letting other people push the actual website pages.

**Comment by didierverna** [comment]
I agree about not including the generated stuff in the repo.

When collaborative editing occurs though, it makes sense that people other than the actual webmaster want to check the generated pages (to see if their changes are correct), even if they're not the ones that push to the hosting service. That's why I though of separating the actual secrets from the public data.

**Comment by Shinmera** [comment]
Okey. I can remove it from the repository, but I'll need to do a history rewrite (and thus a force push) for that. You'll have to fetch & reset to continue using the repository after that. I'll do that over the weekend if that's okey.

Sure, but for that the secrets don't really need to be correct. You can just mash some values in there to get things to generate. The Google Map will be missing with an invalid key, and the registration form won't work, but that shouldn't be a problem, right?

**Comment by didierverna** [comment]
Well, right. If the generated pages aren't included in the repo anymore, it doesn't matter if they contain bogus data.
