### ISSUE TITLE
Factorize some information

### ISSUE THREAD

**Issue by didierverna** [european-lisp-symposium/els-web#2]
Persons and sponsors may (and do) appear in several (many) of the ELS editions. It's a shame that we have to redefine everything in every edition. Hence, there should be a place to define global information shared by all editions.

**Comment by Shinmera** [comment]
I've had this approach in an earlier revision, but got rid of it again because the information changes a lot between conferences. Thus you can't simply copy in all "global information" into a specific edition. For example, the roles of each person change between every conference, making it not feasible to merely import them.

There is value in allowing an "import and override", but I'd have to think about how to facilitate this without making the general case confusing or annoying. Maybe something like a `define-person` and an `import-person` that looks the same, but the latter copies all unspecified data from the global pool if it can?

**Comment by didierverna** [comment]
1. Sponsor information don't change a lot. When it does (most of the time, it's the logo), you want that to be reflected in every edition of the symposium. That's why it would be better to have this information stored in a single common place.

2. For people, think of it this way: people are one thing (doesn't change), their role is something else (does change). If something changes in the people (like their website although we don't care much), you want that to be updated in every edition (just like for sponsors) so it makes sense store this in a common place.

So I'm thinking something along these lines:
;; global
(define-person "Didier Verna" :website ... :other-stuff ...)

;; Edition-local
(add-person "Didier Verna" :roles (:admin :author ...))

**Comment by Shinmera** [comment]
Right, that's what I was thinking as well. I'll see about adding that after the conference.

**Comment by didierverna** [comment]
Yup. No hurry.
