### ISSUE TITLE
Compress Generated HTML

### ISSUE THREAD

**Issue by Shinmera** [european-lisp-symposium/els-web#3]
Adding a compress pass to strip unnecessary whitespace from the resulting HTML would be good to optimise content delivery a bit.

**Comment by Hexstream** [comment]
I don't have a stake in this project, but here's my thoughts about this (non-)issue regardless:

Stripping the whitespace would probably be a waste of time, especially since the site already serves content gzipped when possible. Saving a few dozens of bytes is unlikely to have any actual effect and your optimization efforts are quite probably better spent elsewhere.

Stripping the whitespace would also make the source harder to read (which you may or may not care about), unless you use source maps (which I'm not very familiar with)...

----------------------------------------

Unless I'm misinterpreting [this](https://www.webpagetest.org/result/170330_K6_1GAC/1/performance_optimization/), you're not using HTTP caching right now, which I think would be a more fruitful avenue for optimization.

(If you eventually want to get into the CDN game, I would heartily recommend [CloudFront](https://aws.amazon.com/cloudfront/), which is dirt cheap and (in my personal experience) easy to use once you're set up (I don't remember how easy or hard initial setup was). I'm using it for all my HexstreamSoft stuff, it has cost me only 3.48$ from February 2016 to February 2017 (though I admittedly don't get much traffic and my site is mostly text). Though the 15 minutes invalidation time can be a bit annoying. **edit**: As it happens, "fast invalidations" (~1 minute instead of ~15 minutes) were [announced](https://forums.aws.amazon.com/ann.jspa?annID=4521) pretty much at the same time I said this, though I only learned of it today (4 days later). Yay!)

------------------------------------------

Hope this helps!

**Comment by didierverna** [comment]
FWIW, I agree with Hexstream here.
